
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "sentences.settings")
import django
django.setup()
from sentenceBank.models import *

sources = []

# MainSentence.objects.filter(source="Internet Egyptian Arabic Phrases").delete()

# https://discoverdiscomfort.com/colloquial-egyptian-arabic-phrases/
sources.append([
    ["Hello (basic greeting)", "salaam ‘aleikum", "سلام عليكم"],
    ["Goodbye", "ma’a salaameh", "مع سلامة"],
    ["How’s it going?", "3aamil eh?\nizzayak?\neh akhbaar?\nakhbaarak eh?", "عامل ايه؟\nازيك؟\nايه اخبار؟\nاخبارك ايه؟"],
    ["Fine\nEverything’s good", "kwayyis, kullu tamaam\nalHamdulillah", "كويس،كله تمام\nالحمد لله"],
    ["Excuse me!", "ba3d iznak (or iznik to a female)", "بعد اذنك"],
    ["Sorry (bumping into someone)", "l’il asif", "لال اسِف"],
    ["Pardon me", "law samaHt", "لو سمحت"],
    ["Excuse me, I want to tell you something", "3yiiz a’ool lak ba3d iznak", "عيز اقول لك بعد اذنك"],
    ["Hey, driver!", "ya usTa!", "يى اسطى"],
    ["Officer/sir!", "HaDritak", "حضرتك"],
    ["What’s this, please?", "eh dah min faDlak?", "اية دة من فضلك"],
    ["How much is this?", "bikam dah?", "بكم دة"],
    ["I want…", "ana 3ayiiz…", "انا عيز"],
    ["It’s too expensive!\nIt’s so much!\nI will pay…", "ghaali ‘awwi!\nktiir awwi!\nana badfa3…", "غالي اوي\nكتير اوي\nانا بدفع"],
    ["OK", "maashi\ntayyib\ntamaam\nokey", "ماشي\nطيب\nتمام\nاوكي"],
    ["Yes, of course/thank you", "aywa, tab3an/shukran", "ايوى، تبعن\شكرا"],
    ["No, sorry/thank you", "la, aasif/shukran", "لا، اسف\شكرا"],
    ["You’re welcome", "‘afwan", "عفواً"],
    ["May I [please]?", "mumken [min faDlak]?", "ممكن؟"],
    ["May I take a photo here?", "mumken akhud Surah hina?", "ممكن اخد صورة هنا؟"],
    ["May I look, please?", "mumken ashuuf min faDlak?", "ممكن اشوف من فضلك؟"],
    ["May I go in from here?", "momken adkhul min hina?", "ممكن ادخل من هنا؟"],
    ["I just want to look", "ana 3ayiiz ashuuf bas", "انا عيز اشوف بس"],
    ["Thanks", "shukran", "شكرا"],
    ["A thousand thanks", "alf shokr", "الف شكر"],
    ["Where is this? / the Bathroom, please?", "fayn dah/il Hammaam, min faDlak?", "فين ده؟\nفين الحمام من فضلك؟"],
    ["I go this way?", "baruuH zayy kida?", "بروح زي كدا؟"],
    ["straight ahead", "3ala Tuul", "على طول"],
    ["Finished!\nIt’s over!\nI’m done!", "khallaS!", "!خلص"],
    ["I don’t need this", "la, ana mish miHtaag dah", "لا، انا مش محتاج ده"],
    ["I don’t know.", "ana mish 3aarif/3aarfa", "انا مش عارف\عارفة"],
    ["Please go ahead!\nPlease sit!\nPlease take this!", "itfaDDal/itfaDDali", "إتفضّـل"]
])

# https://storylearning.com/learn/arabic/arabic-tips/arabic-phrases

sources.append( [
    ["Hello (peace upon you).", "Salaam ‘aleikum.", "سلام عليكم"],
    ["Welcome.", "Ahlan.", "اهلا"],
    ["Good morning.", "Saba7 elkheer.", "صباخ الخير"],
    ["Good morning (response).", "Saba7 el noor.", "صباح النور"],
    ["Good evening.", "Massa elkheer.", "مساء الخير"],
    ["Good evening (response).", "Massa el noor.", "مساء النور"],
    ["How’s it going?", "3aamil eh / 3ammluh ay?", "عامل ايه؟ / عاملة ايه؟"],
    ["How are you?", "Izzayak / Izzayik?", "ازيك؟"],
    ["What’s up?", "Eh akhbaar? / Akhbaarak eh?", "اخبارك ايه؟ / ايه اخبار؟"],
    ["I am good.", "Ana Kwayyis / kwayISSuh", "انا كويس / انا كويسة"],
    ["Everything’s great.", "Kullu tamaamh.", "كله تمام"],
    ["Nice to meet you.", "Forsa sa3eeda.", "فرصة سعيدة."],
    ["Nice to meet you, as well.", "Ana As3ad.", "انا اسعد"],
    ["Thanks be to God.", "alHamdulillah", "الحمد لله"],
    ["Thank you.", "Shokran.", "شكرا"],
    ["A thousand thanks.", "Alf shokr.", "الف شكر"],
    ["You’re welcome.", "3afwan.", "عفوا"],
    ["Pardon me – please.", "Law sama7t.", "لو سمحت"],
    ["Please go ahead.", "Etfutdll / Etfutdlee.", "اتفضل اتفضلي. (masculine followed by feminine)"],
    ["Excuse me.", "Ba3d izznuck / izznick.", "بعد اذنك"],
    ["I am sorry.", "Ana awsiff / awssfa.", "انا تسف – اسفة."],
    ["Can you help me, please?", "Momken tsa3dni / tsa3dini, law samht?", "ممكن تساعدني / ممكن تساعديني (feminine)"],
    ["No problem!", "Mish mooshkela!", "مش مشكلة"],
    ["Do you know the way?", "Enta a3ruff / entee a3ruffuh altaree?", "انت عارف – انتي عارفة الطريق؟"],
    ["I don’t understand", "Ana mish fahem / fahmuh.", "انا مش فاهم – فاهمة"],
    ["I don’t know.", "Ana mish 3arf / 3arfaa.", "مش عارف – عارفة"],
    ["I am learning Arabic.", "Ana bawta3alm 3rabee.", "انا بتعالم عربي"],
    ["I don’t speak Arabic.", "Mish betkelum 3rabee.", "انا مش بتكلم عربي"],
    ["Can you speak slowly?", "Moomkin tetkehlim/ee bera7aw? (masculine followed by feminine “can you…”)", "ممكن تتكلم – تتكلمي براحة؟"],
    ["This is very expensive.", "Daw 5awlee owee.", "دة غالي اوي"],
    ["This is too much.", "Daw kiteer owee.", "دة كتير اوي"],
    ["I will pay…", "Ana badfa3…", "انا بدفع"],
    ["I’m finished – done.", "Khalass!", "خلاص"],
    ["Hey driver!", "Ya usta!", "يا اسطى"],
    ["Next street.", "Elshare3 elgaya.", "الشارء الي جي"],
    ["Straight ahead.", "3ala tool.", "على طول"],
    ["Left – right.", "Yameen / shamel.", "يمين – شمال."],
    ["How expensive is the ticket?", "Eltazkara bkam?", "التزكارة بكم؟"],
    ["I am hungry/I am thirsty.", "Ana ga3an / ana 3atschan.", "انا جعان – انا عتشان."],
    ["Can I pay with a credit card?", "Momken adfa3 belkart?", "ممكن ادفع بلكارت؟"],
    ["May I enter here?", "Moomkin edkhol hena?", "ممكن ادخل هنا؟"],
    ["I want to buy this.", "Eyeizz / eyezuh ehshteree daw.", "عايز / عايزة اشتري دة"],
    ["What does….mean in Arabic?", "Ya3ni ay…. bel 3rabi?", "يعني ايه…..بل عربي؟"],
    ["My name is….", "Esmee….", "اسمي"],
    ["I am from…", "Ana men…", "انا من"],
    ["I am….years old.", "3ndy…..sinuh", "عندي….سنة"],
    ["Yes.", "Aywa.", "ايوه"],
    ["No.", "La2.", "لا"],
    ["Sometimes.", "Sa3eht.", "ساعات"],
    ["All the time.", "3law tool.", "على طول"],
    ["Never.", "Ebedehn.", "ابدان"],
    ["Ok.", "Maashi.", "ماشى"],
    ["Excellent.", "Tamaam.", "تمام"],
    ["Alright.", "Tayyib.", "طيب"],
    ["Of course.", "Tawba3n / akeed.", "تبعن / اكيد"],
    ["Congratulations!", "Mabrook!", "مبروك"],
    ["Happy birthday!", "3eed meelehd sa3eed!", "عيد ميلاد سعيد"],
    ["God-willing.", "InSHAallah.", "إن شاء لله"],
    ["Goodbye.", "ma’a salaameh.", "مع سلامة"],
    ["Happy to see you.", "Mawbsoot 3lashane ashoofuck/fick.", "مبسوط علشان اشوفك"],
    ["See you soon.", "Hashoofuck /fick ooreyib.", "هشوفك / هشوفك اوريب"],
    ["What is your name?", "Esmak/ick eh?", "اسمك ايه؟"],
    ["Where are you from?", "Enta / entee menane?", "انت انتي من اين؟ (masculine “you” and femine “you” are first two words here)"],
    ["Where do you live?", "Sakin fane / sakina fane?", "ساكن فين؟ – ساكنة فين؟"],
    ["How much is this?", "Bikam daw?", "بكم دة؟"],
    ["What time is it?", "Elsa3a kam?", "الساعه كم؟"],
    ["Where is the bathroom?", "Fane el7mmam?", "فين الحمام؟"],
    ["Can I have a menu/coffee/water/shisha?", "Moomkin menu/awhuwu/maya/shisha?", "ممكن منو / قهوة / مايا / شيشا؟"],
    ["Where are you?", "Enta / entee fane?", "انت – انتي فين؟"],
    ["Do you speak English?", "Betkehlm/ee Englizee? (masculine followed by feminine “do you speak…”)", "بتتكلم- بتتكلمي انجليزي؟"],
])

# https://talkinarabic.com/egyptian/arabic-phrases/

sources.append([
    ["Hello", "salaam ‘alei-kum", "سلام عليكم"],
    ["Goodbye", "ma’aa es-sa-la-ma", "مع السلامة"],
    ["Yes", "Ah", "آه"],
    ["No", "La'", "لا"],
    ["Thanks", "Shuk-ran", "شُكْرَاً"],
    ["You're welcome", "Al afow", "العَفو"],
    ["Be safe (addressing a male)", "Tes-lam", "تِسلَم"],
    ["Be safe (addressing a female)", "Tes-lami", "تِسلَمي"],
    ["My dear (literally: My love)", "Ha-bibi", "حبيبي"],
    ["Hey, honey", "Ya 3a-sal", "يا عَسَل"],
    ["How are you doing?", "3aa-mil eh? iz-zay-ak?", "عامل ايه؟ ازيك؟"],
    ["How are things? (Any updates?)", "eh El-akh-baar?", "ايه الأخبار؟"],
    ["Fine", "kway-yis ta-maam", "كُوَيس تَمَام"],
    ["Thank God!", "Al-hamdu-lillah", "الحَمْدُ لِله"],
    ["Sorry (for a sincere apology)", "Aa-sif (If you're a male)", "Aa-sfa (If you're a female)", "آسف (If you're a male)", "آسفة (If you're a female)"],
    ["Sorry (for a non-harmful incident)", "Ma'lish", "مَعلِش"],
    ["Pardon me (addressing a male)", "law samaHt", "لَو سَمَحْت"],
    ["Pardon me (addressing a female)", "law sa-ma-Hti", "لَو سَمَحتي"],
    ["Hey, driver!", "Yas-Ta!", "يا اسطى"],
    ["What’s this, please? (addressing a male)", "eh dah law sa-ma-Ht?", "ايه ده لَو سَمَحت؟ (addressing a male)", "eh dah law sa-ma-Hti (addressing a female)"],
    ["How much is this?", "Bi-kam da?", "بِكام دا؟"],
    ["I want…", "ana 3ay-yiz…", "أنا عَايز"],
    ["Too much!", "ki-tir aw-wi!", "كتير أوي"],
    ["I won't pay more than..", "Mish had-fa3 ak-tar min…", "مِش هَدفع أكْتَر مِن"],
    ["OK", "Maa-shi Tay-yib tama-am Okey", "ماشي طيب تمام اوكي"],
    ["Yes, of course", "aywa, tab-3an", "أيوَة، طَبعَاً"],
    ["No, never", "La, mos-ta-Hil", "لا، مُستَحيل"],
    ["May I please?", "Mom-ken?", "مُمْكِن؟"],
    ["May I take a photo?", "Mom-ken a-khud Surah?", "مُمْكِن آخُد صُورة؟"],
    ["May I look, please?", "Mom-ken ashuuf?", "ممكن اشوف من فضلك؟"],
    ["May I go in from here?", "Mom-ken ad-khul min hina?", "ممكن أدخل من هِنا؟"],
    ["I just want to take a look", "ana bas bat-far-rag", "انا بس بَتفَرَّج"],
    ["Thanks a lot (literally: a thousand thanks)", "alf shokr", "أَلْف شُكْر"],
    ["Where is this?", "fen dah?", "فِين دَه؟"],
    ["I go this way?", "kida?", "كِدا؟"],
    ["straight ahead", "Ta-wa-li", "طَوَالي"],
    ["the shortest way?", "da Aksar tareek?", "Is this دا أقصَر طريق؟"],
    ["It’s done!", "Kha-las", "!خَلاص"],
    ["no need", "Ma-losh lo-zoom", "مَلُوش لُزُوم"],
    ["I don’t know.", "mish 3aa-rif (in case the speaker is a male)", "mish 3aar-fa (in case the speaker is a female)", "مِشْ عَارِف مِشْ عَارفَة"],
    ["Here you go! (please accept to have or take or being invited to do something)", "Itfad-dal (in case you are addressing a male)", "Itfad-da-li (in case you are addressing a female)", "اتْفَضّـل اتْفَضَلي"],
    ["I'm not available. Sorry", "Asif mish fady (in case the speaker is a male)", "Asfa mish fad-ya (in case the speaker is a female)", "آسِف مش فاضي آسفة مش فاضية"],
    ["Now?", "Del-wa'-ti?", "دِلوَقتِي"],
    ["It won't work out", "Mish hay-yen-fa3", "مِش هينفغ"],
])


for source in sources:
    for sentence in source:
        # in case there is no MainSentence that has either the same english or arabic as the sentence, create it
        if not MainSentence.objects.filter(english=sentence[0]).exists() and not MainSentence.objects.filter(arabic=sentence[1]).exists():
            MainSentence.objects.create(
                english=sentence[0], 
                arabic=sentence[2], 
                transliteration=sentence[1], 
                dialect='Egyptian',
                source="Internet Egyptian Arabic Phrases"
        )