# Generated by Django 4.2.5 on 2023-10-01 08:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concordance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=500)),
                ('arabic', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MainSentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=500)),
                ('arabic', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceVariation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=500)),
                ('arabic', models.CharField(max_length=500)),
                ('mainSentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentenceBank.mainsentence')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=500)),
                ('arabic', models.CharField(max_length=500)),
                ('mainSentences', models.ManyToManyField(to='sentenceBank.mainsentence')),
                ('sentenceVariations', models.ManyToManyField(to='sentenceBank.sentencevariation')),
            ],
        ),
        migrations.AddField(
            model_name='mainsentence',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentenceBank.topic'),
        ),
        migrations.CreateModel(
            name='ConcordanceQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(max_length=500)),
                ('wrong_answer', models.CharField(max_length=500)),
                ('concordance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentenceBank.concordance')),
            ],
        ),
        migrations.AddField(
            model_name='concordance',
            name='words',
            field=models.ManyToManyField(to='sentenceBank.word'),
        ),
    ]
