# Generated by Django 4.2.5 on 2023-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceBank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concordance',
            name='arabic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mainsentence',
            name='arabic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sentencevariation',
            name='arabic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='arabic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
