# Generated by Django 4.2.5 on 2023-10-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceBank', '0002_alter_concordance_arabic_alter_mainsentence_arabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concordancequestion',
            name='wrong_answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
