# Generated by Django 4.2.5 on 2023-10-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceBank', '0003_alter_concordancequestion_wrong_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConcordanceQuestion',
            new_name='ConcordanceExercise',
        ),
        migrations.RenameField(
            model_name='concordanceexercise',
            old_name='question',
            new_name='prompt',
        ),
    ]
