# Generated by Django 4.2.5 on 2023-10-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceBank', '0004_rename_concordancequestion_concordanceexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concordanceexercise',
            name='question',
            field=models.CharField(default='...', max_length=500),
            preserve_default=False,
        ),
    ]
