# Generated by Django 4.2.5 on 2023-10-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceBank', '0005_concordanceexercise_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsentence',
            name='dialect',
            field=models.CharField(choices=[('MSA', 'MSA'), ('Egyptian', 'Egyptian')], default='MSA', max_length=50),
        ),
    ]
