# Generated by Django 4.2.5 on 2023-10-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceBank', '0006_mainsentence_dialect'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsentence',
            name='transliteration',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
