# Generated by Django 4.2.5 on 2023-10-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentenceBank', '0007_mainsentence_transliteration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainsentence',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mainsentence',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentenceBank.topic'),
        ),
    ]
